server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: application/json, application/xml
general:
  purpose:
    oauth:
      token:
        key-file-name: generalpurpose.jks
        key-pair: generalpurpose
        key-password: gpurposeKey
      client:
        id: OAuth-service
        secret:
        accessTokenUrl: http://oauth-service/oauth/token